name: notes back ci
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout do repositorio
              uses: actions/checkout@v1
            - name: Deploy para meu hosting
              uses: easingthemes/ssg-deploy@main
              env:
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rltgoDzvO --delete"
                SOURCE: "."
                REMOTE_HOST: ${{secrets.REMOTE_HOST}}
                REMOTE_USER: ${{secrets.REMOTE_USER}}
                REMOTE_PORT: ${{secrets.REMOTE_PORT}}
                TARGET: ${{secrets.REMOTE_TARGET}}

